/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#111c2d',
        'surface-dim': '#cfdaf2',
        'on-tertiary-container': '#4a3f00',
        'secondary-container': '#6cf8bb',
        'on-tertiary-fixed': '#211b00',
        'tertiary-fixed-dim': '#e2c62d',
        'tertiary-container': '#c4aa01',
        'on-primary-fixed-variant': '#004395',
        'surface-container-highest': '#d8e3fb',
        'error-container': '#ffdad6',
        tertiary: '#6d5e00',
        'on-secondary-fixed': '#002113',
        background: '#f9f9ff',
        'outline-variant': '#c2c6d6',
        'on-secondary-fixed-variant': '#005236',
        surface: '#f9f9ff',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'surface-container': '#e7eeff',
        'secondary-fixed-dim': '#4edea3',
        outline: '#727785',
        'on-secondary-container': '#00714d',
        'tertiary-fixed': '#ffe24c',
        'surface-container-high': '#dee8ff',
        'primary-container': '#2170e4',
        'surface-tint': '#005ac2',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        'secondary-fixed': '#6ffbbe',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#263143',
        secondary: '#006c49',
        'surface-bright': '#f9f9ff',
        'primary-fixed-dim': '#adc6ff',
        primary: '#0058be',
        'on-background': '#111c2d',
        'surface-variant': '#d8e3fb',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#524600',
        'on-surface-variant': '#424754',
        'on-error': '#ffffff',
        'primary-fixed': '#d8e2ff',
        'inverse-on-surface': '#ecf1ff',
        'on-primary-fixed': '#001a42',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f0f3ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'gap-default': '24px',
        unit: '8px',
        'touch-target-min': '56px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        main: ['"Atkinson Hyperlegible Next"', 'sans-serif'],
      },
      fontSize: {
        'label-md':          ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-xl':       ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg':       ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile':['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-md':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-lg':           ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'label-lg':          ['18px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '700' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      animation: {
        'soft-pulse': 'soft-pulse 3s infinite ease-in-out',
        'card-flip': 'card-flip 0.5s ease-in-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
        'bounce-in': 'bounce-in 0.5s ease-out',
      },
      keyframes: {
        'soft-pulse': {
          '0%, 100%': { transform: 'scale(1)', filter: 'drop-shadow(0 0 0px rgba(78,222,163,0))' },
          '50%':       { transform: 'scale(1.02)', filter: 'drop-shadow(0 0 15px rgba(78,222,163,0.4))' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'bounce-in': {
          '0%':   { opacity: '0', transform: 'scale(0.8)' },
          '70%':  { transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
};
